name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: zip gruvbox.tdesktop-theme background.png colors.tdesktop-theme
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: gruvbox.tdesktop-theme
