schema_version = "1.0.0"
id = "PieMenu_Everywhere"
version = "1.4.5"
name = "PieMenu Everywhere"
tagline = "Maximize your efficiency with PieMenu Everywhere"
maintainer = "Deathshot747 <thatsdeathshot@gmail.com>"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
tags = ["User Interface", "Pipeline", "3D View", "Node"]
