# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml

[notification]
font_size = 7

[rofi]
# global rofi configuration`
scale = 9 # rofi default scaling

[volume]
boost = true
boost_limit = 150
